# .github/workflows/deploy.yml
name: Build and Deploy to Infomaniak

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SSH_USERNAME }}
          server: ${{ secrets.SSH_HOST }}
          password: ${{ secrets.FTP_PASSWORD }} # You can keep using your password secret
          port: 22
          # Use the path to your web root on Infomaniak
          remote_path: /sites/
          # Sync everything from the root
          local_path: .
          # Files to exclude from transfer
          # IMPORTANT: For Next.js/Node, we don't want to send src or node_modules
          # because the build is finished.
          args: '-avz --exclude="node_modules" --exclude=".git*" --exclude=".github" --exclude="src"'
