# .github/workflows/deploy.yml

name: Build and Deploy to Infomaniak

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Sync to Infomaniak via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: sftp
          port: 22
          # Ensure this path exists. Based on your previous log,
          # make sure /sites/ is the correct absolute path on the server.
          server-dir: /sites/
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            src/
            README.md
            .gitignore
